--- #YAML:1.0
name:                Test-TAP-Model
version:             0.09
abstract:            ~
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.31
distribution_type:   module
requires:     
    Method::Alias:                 0
    Test::Harness:                 2.64
    Test::More:                    0.53
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
