---
name: Test-TAP-Model
version: 0.04
author: ~
abstract: |-
  Accessible (queryable, serializable object) result collector
  for L<Test::Harness::Straps> runs.
license: perl
requires:
  perl: >= 5.008
build_requires:
  Test::More: 0.53
provides:
  Test::TAP::Model:
    file: lib/Test/TAP/Model.pm
    version: 0.04
  Test::TAP::Model::File:
    file: lib/Test/TAP/Model/File.pm
  Test::TAP::Model::Subtest:
    file: lib/Test/TAP/Model/Subtest.pm
generated_by: Module::Build version 0.261
