---
name: Test-TAP-Model
version: 0.06
author: ~
abstract: |-
  Accessible (queryable, serializable object) result collector
  for L<Test::Harness::Straps> runs.
license: perl
requires:
  perl: 5.8
build_requires:
  Method::Alias: 0
  Test::More: 0.53
provides:
  Test::TAP::Model:
    file: lib/Test/TAP/Model.pm
    version: 0.06
  Test::TAP::Model::Consolidated:
    file: lib/Test/TAP/Model/Consolidated.pm
  Test::TAP::Model::File:
    file: lib/Test/TAP/Model/File.pm
  Test::TAP::Model::File::Consolidated:
    file: lib/Test/TAP/Model/File/Consolidated.pm
  Test::TAP::Model::Subtest:
    file: lib/Test/TAP/Model/Subtest.pm
generated_by: Module::Build version 0.2611
