--- #YAML:1.0
name: Test-TAP-Model
version: 0.02
author: ~
abstract: |-
  Accessible (queryable, serializable object) result collector
  for L<Test::Harness::Straps> runs.
license: perl
requires:
  perl: '>= 5.008'
build_requires:
  Test::More: 0
provides:
  Test::TAP::Model:
    file: lib/Test/TAP/Model.pm
    version: 0.02
  Test::TAP::Model::File:
    file: lib/Test/TAP/Model/File.pm
    version: 0.02
  Test::TAP::Model::Subtest:
    file: lib/Test/TAP/Model/Subtest.pm
    version: 0.01
generated_by: Module::Build version 0.261
